# Generated by Django 3.2.23 on 2024-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('score_audience', models.CharField(max_length=100)),
                ('score_critic', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
